##应用名
nacos:
  ##主机名
  hostname: nacos-node1
  ##环境变量
  environment:
    ##约束此节点
    constraint: group==node1
    RDS_HOSTNAME: rm-wz9m78y908iigw5j3.mysql.rds.aliyuncs.com
    RDS_USERNAME: nacos
    RDS_PASSWORD: nacos(*&987
    RDS_DB_NAME: nacos
    ##nacos集群列表
    NODE_LIST: 'nacos-node1:8848 nacos-node2:8848 nacos-node3:8848'
  #端口
  ports:
    - '8848:8848/tcp'
  restart: always
  memswap_limit: 0
  labels:
    aliyun.scale: '1'
  shm_size: 0
  image: 'registry.cn-shenzhen.aliyuncs.com/hhglobal/biostime:nacos'
  memswap_reservation: 0
  kernel_memory: 0
  mem_limit: 0
  name: nacos-node1
